# Generated by Django 2.1 on 2018-08-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leave', '0002_auto_20180813_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
